services:
  mariadb:
    restart: always
    image: mariadb:11.7.1-ubi9-rc
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_USER_FILE:          /run/secrets/db_user_name
      MARIADB_PASSWORD_FILE:      /run/secrets/db_user_password
      MARIADB_DATABASE_FILE:      /run/secrets/db_name
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_user_name
      - db_user_password
      - db_name
    networks:
      - backend

  wordpress:
    image: wordpress:6.7.1-php8.3-fpm
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST:          mariadb  # use the id of db container
      WORDPRESS_DB_USER_FILE:     /run/secrets/db_user_name
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_user_password
      WORDPRESS_DB_NAME_FILE:     /run/secrets/db_name
    volumes:
      # mountpoint must be exactly the same as the wordpress_data mountpoint
      # in the nginx container
      - wordpress_data:/var/www/html
    secrets:
      - db_user_name
      - db_user_password
      - db_name
    networks:
      - backend

  nginx:
    image: nginx:1.27.3
    restart: always
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - nginx_logs:/etc/nginx/logs
      - wordpress_data:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - backend
    ports:
      - "80:80"

volumes:
  mariadb_data:
    external: false
  wordpress_data:
    external: false
  nginx_logs:
    external: false

secrets:
  db_root_password:
    file: secrets/db-root-password.txt
  db_user_name:
    file: secrets/db-user-name.txt
  db_user_password:
    file: secrets/db-user-password.txt
  db_name:
    file: secrets/db-name.txt

networks:
  backend:
