name: entry

services:
  proxy:
    image: jc21/nginx-proxy-manager:2.12.3
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "80:80"
      - "9000:81"
      - "443:443"
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD__FILE: /run/secrets/db_user_password
      DB_MYSQL_NAME: "npm"
    secrets:
      - db_user_password
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - default
      - wordpress_backend

  db:
    image: jc21/mariadb-aria:10.11.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD__FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD__FILE: /run/secrets/db_user_password
      MARIADB_AUTO_UPGRADE: "1"
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - ./mysql:/var/lib/mysql

  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.5-debian
    restart: unless-stopped
    environment:
      COLLECTIONS: "crowdsecurity/nginx"
      GID: "${GID:-1000}"
    depends_on:
      - "proxy"
    volumes:
      - crowdsec_config:/etc/crowdsec
      - crowdsec_data:/var/lib/crowdsec/data
      - ./data/logs:/var/log/nginx:ro
      - ./crowdsec/acquis.d:/etc/crowdsec/acquis.d
      - "${JOURNALCTL_VOL:-/var/log/journal}:/run/log/journal"
    ports:
      # expose this port for localhost access (but if NAT loopback was supported, we could avoid exposing this port and make a proxy host for this)
      - "8999:8080"
    networks:
      - default
      - wordpress_backend

  metabase:
    # this special image copies metabase-sql.zip to the image, as a workaround for the previously deprecated method of configuring metabase on a separate container from crowdsec
    build: ./crowdsec/dashboard
    restart: unless-stopped
    environment:
      MB_DB_FILE: /data/metabase.db
      MGID: "${GID:-1000}"
    depends_on:
      - "crowdsec"
    volumes:
      # re-use crowdsec data volume so we can see its files too
      - crowdsec_data:/metabase-data

volumes:
  nginx_config:
    external: false
  nginx_logs:
    external: false
  crowdsec_config:
    external: false
  crowdsec_data:
    external: false

secrets:
  db_root_password:
    file: secrets/db-root-password.txt
  db_user_password:
    file: secrets/db-user-password.txt

networks:
  wordpress_backend:
    external: true
